import assert from 'node:assert/strict';
import test from 'node:test';

import { renderXcodeVersionConfiguration } from './sync-version.mjs';

test('renders stable Xcode version settings from the release manifest', () => {
  assert.equal(
    renderXcodeVersionConfiguration('{"version":"0.4.0","release":true}'),
    [
      '// Generated by .github/scripts/sync-version.mjs. Do not edit.',
      'MARKETING_VERSION = 0.4.0',
      'TECHNE_UPDATE_CHANNEL = stable',
      '',
    ].join('\n'),
  );
});

test('uses the base marketing version and prerelease update channel', () => {
  const configuration = renderXcodeVersionConfiguration(
    '{"version":"1.2.3-beta.4","release":false}',
  );

  assert.match(configuration, /^MARKETING_VERSION = 1\.2\.3$/m);
  assert.match(configuration, /^TECHNE_UPDATE_CHANNEL = beta$/m);
});
