import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { parseManifest } from './release-manifest.mjs';

const MANIFEST_PATH = 'Config/Release/manifest.json';
const XCODE_VERSION_PATH = 'Config/Generated/Version.xcconfig';

export function renderXcodeVersionConfiguration(manifestSource) {
  const manifest = parseManifest(manifestSource);
  return [
    '// Generated by .github/scripts/sync-version.mjs. Do not edit.',
    `MARKETING_VERSION = ${manifest.version.base}`,
    `TECHNE_UPDATE_CHANNEL = ${manifest.version.channel}`,
    '',
  ].join('\n');
}

export async function syncXcodeVersion({ check = false } = {}) {
  const manifestSource = await readFile(MANIFEST_PATH, 'utf8');
  const expected = renderXcodeVersionConfiguration(manifestSource);

  if (check) {
    const actual = await readFile(XCODE_VERSION_PATH, 'utf8').catch(() => '');
    if (actual !== expected) {
      throw new Error(
        `${XCODE_VERSION_PATH} is out of date. Run: node .github/scripts/sync-version.mjs`,
      );
    }
    return;
  }

  await writeFile(XCODE_VERSION_PATH, expected, 'utf8');
}

async function main() {
  const args = process.argv.slice(2);
  if (args.some((argument) => argument !== '--check')) {
    throw new Error('Usage: node .github/scripts/sync-version.mjs [--check]');
  }
  await syncXcodeVersion({ check: args.includes('--check') });
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  main().catch((error) => {
    console.error(`::error::Version synchronization failed: ${error.message}`);
    process.exitCode = 1;
  });
}
